global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tbd-bot'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tbd-bot:8080']
