name: Docker CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Log in to Azure Container Registry
    - name: Log in to ACR
      run: |
        az acr login --name tbdbotregistry

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t tbdbotregistry.azurecr.io/tbd-bot:latest .

    # Push the Docker image to ACR
    - name: Push Docker image
      run: |
        docker push tbdbotregistry.azurecr.io/tbd-bot:latest

    # Deploy to Azure Web App (Optional: If using Azure App Service)
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>
        images: tbdbotregistry.azurecr.io/tbd-bot:latest