# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tbdbot-cicd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tbdbotregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c002e078479e424799782ce3ced8f2c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1359188a2b8c44c5a48a03194a17ecd2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tbdbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c002e078479e424799782ce3ced8f2c5 }}/tbdbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tbdbot-cicd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c4ee803c0cf846fba01cc8f693c34c78 }}
        images: 'tbdbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c002e078479e424799782ce3ced8f2c5 }}/tbdbot:${{ github.sha }}'